---
title: "Task1"
output: html_document
date: "2024-10-24"
---

```{r, echo=FALSE, message=FALSE}
# Load libraries
library(tidyverse)
library(psych)
library(glmnet)
```

```{r}
# Data Generation
set.seed(123)

n <- 1000  
x_1 <- rnorm(n, mean = 0, sd = 1)
x_2 <- rnorm(n, mean = 0, sd = 1)
e <- rnorm(n, mean = 0, sd = 1)
epsilon <- rnorm(n, mean = 0, sd = 1)

x_3 <- (2/3) * x_1 + (2/3) * x_2 + (1/3) * e

beta_1 <- 2
beta_2 <- 3
y <- beta_1 * x_1 + beta_2 * x_2 + epsilon

hist(y)
```

```{r}
# check correlation
cor_matrix <- cor(cbind(x_1, x_2, x_3, e, epsilon))
print(cor_matrix)

```

```{r}
# Base Linear Regression
data_base <- data.frame(x_1, x_2, x_3, y)
lm_base <- lm(y ~ x_1 + x_2 + x_3, data = data_base)
summary(lm_base)
```

```{r}
# Lasso regression model
X <- as.matrix(cbind(x_1, x_2, x_3))  
lasso_model <- glmnet(X, y, alpha = 1, family="gaussian")

plot(lasso_model)
title("Lasso Model Path for X1, X2, X3")

```

```{r}
# Cross validastion to find best lambda
cv_lasso_model <- cv.glmnet(X, y, alpha = 1, family="gaussian")
best_lambda <- cv_lasso_model$lambda.1se
print(paste("Best Lambda:", best_lambda))
```

```{r}
# MSE calculation
predicted_y <- predict(cv_lasso_model, s = best_lambda, newx = X)
mse <- mean((y - predicted_y)^2)
mse <- round(mse, 2)
print(paste("Mean Squared Error:", mse))

```

```{r}
# Experiment with different noise levels in e
for (i in seq(1, 5, by=1)){
  e <- rnorm(n, mean = 0, sd = i)
  x_3 <- (2/3) * x_1 + (2/3) * x_2 + (1/3) * e
  X <- as.matrix(cbind(x_1, x_2, x_3))  
  temp_lasso_model <- glmnet(X, y, alpha = 1, family="gaussian")  
  plot(temp_lasso_model, label=TRUE)
  title(paste0("Lasso model with e's sd = ", i))
}
```

